/*
 * Generated by MTK SP DrvGen Version 03.13.6 for MT6580. Copyright MediaTek Inc. (C) 2013.
 * Fri Apr 28 13:39:40 2017
 * Do Not Modify the File.
 */

#ifndef __CUST_AUXADC_TOOL_H
#define __CUST_AUXADC_TOOL_H


#define AUXADC_TEMPERATURE_CHANNEL     0
#define AUXADC_TEMPERATURE1_CHANNEL     1


#endif //_CUST_AUXADC_TOOL_H


